version: 2.1

orbs:
  docker: circleci/docker@0.5.20

executors:
  default_executor:
    working_directory: '~/project'
    docker:
      - image: 'docker:17.05.0-ce-git'

attach_workspace: &attach_workspace
    attach_workspace:
        at: '.'

persist_workspace: &persist_workspace
    persist_to_workspace:
        root: '.'
        paths: [ '.' ]

fan_in: &fan_in
    executor: default_executor
    steps: [ { run: 'whoami' } ]

build_image: &build_image
    executor: default_executor
    steps:
        - *attach_workspace
        - setup_remote_docker
        - docker/check:
            docker-username: DOCKER_USER
            docker-password: DOCKER_PASS
        - docker/build:
            path: "${DOCKER_PATH}"
            image: "halplatform/hal-build-environments"
            tag: "${DOCKER_TAG}"
        - docker/push:
            image: "halplatform/hal-build-environments"
            tag: "${DOCKER_TAG}"

workflows:
    version: 2
    pipeline:
        jobs:
            - fetch_code:
                filters:
                    branches: { only: master }

            - build_linux_centos6:
                requires: [ fetch_code ]
            - build_linux_centos7:
                requires: [ fetch_code ]
            - build_linux_debian8:
                requires: [ fetch_code ]
            - build_linux_debian9:
                requires: [ fetch_code ]

            - fan_in_1:
                requires:
                    - build_linux_centos6
                    - build_linux_centos7
                    - build_linux_debian8
                    - build_linux_debian9

            - build_dotnet11:
                requires: [ fan_in_1 ]
            - build_dotnet20:
                requires: [ fan_in_1 ]
            - build_dotnet21:
                requires: [ fan_in_1 ]
            - build_dotnet22:
                requires: [ fan_in_1 ]

            - fan_in_2:
                requires:
                    - build_dotnet11
                    - build_dotnet20
                    - build_dotnet21
                    - build_dotnet22

            - build_awscli1_11:
                requires: [ fan_in_2 ]
            - build_awscli1_14:
                requires: [ fan_in_2 ]
            - build_awscli1_16:
                requires: [ fan_in_2 ]

            - build_terraform0_11:
                requires: [ fan_in_2 ]
            - build_terraform0_12:
                requires: [ fan_in_2 ]

            - build_docker17_06:
                requires: [ fan_in_2 ]
            - build_docker18_03:
                requires: [ fan_in_2 ]

            - fan_in_3:
                requires:
                    - build_awscli1_11
                    - build_awscli1_14
                    - build_awscli1_16
                    - build_terraform0_11
                    - build_terraform0_12
                    - build_docker17_06
                    - build_docker18_03

            - build_python_27_debian9:
                requires: [ fan_in_3 ]
            - build_python_27_centos7:
                requires: [ fan_in_3 ]
            - build_python_36_centos7:
                requires: [ fan_in_3 ]
            - build_python_36_debian9:
                requires: [ fan_in_3 ]

            - fan_in_4:
                requires:
                    - build_python_27_debian9
                    - build_python_27_centos7
                    - build_python_36_centos7
                    - build_python_36_debian9

            - build_node_48:
                requires: [ fan_in_4 ]
            - build_node_613:
                requires: [ fan_in_4 ]
            - build_node_810:
                requires: [ fan_in_4 ]
            - build_node_1010:
                requires: [ fan_in_4 ]

            - fan_in_5:
                requires:
                    - build_node_48
                    - build_node_613
                    - build_node_810
                    - build_node_1010

            - build_php_56:
                requires: [ fan_in_5 ]
            - build_php_70:
                requires: [ fan_in_5 ]
            - build_php_71:
                requires: [ fan_in_5 ]
            - build_php_72:
                requires: [ fan_in_5 ]
            - build_php_73:
                requires: [ fan_in_5 ]

            - fan_in_6:
                requires:
                    - build_php_56
                    - build_php_70
                    - build_php_71
                    - build_php_72
                    - build_php_73

            - build_elixir_12:
                requires: [ fan_in_6 ]
            - build_elixir_13:
                requires: [ fan_in_6 ]
            - build_elixir_14:
                requires: [ fan_in_6 ]
            - build_elixir_15:
                requires: [ fan_in_6 ]
            - build_elixir_16:
                requires: [ fan_in_6 ]

jobs:

    fetch_code:
        executor: default_executor
        steps:
            - checkout
            - *persist_workspace

    build_linux_centos6:
        <<: *build_image
        environment: [ { DOCKER_PATH: './linux/centos6/buildpack', DOCKER_TAG: 'centos6-buildpack' } ]
    build_linux_centos7:
        <<: *build_image
        environment: [ { DOCKER_PATH: './linux/centos7/buildpack', DOCKER_TAG: 'centos7-buildpack' } ]
    build_linux_debian8:
        <<: *build_image
        environment: [ { DOCKER_PATH: './linux/debian8/buildpack', DOCKER_TAG: 'debian8-buildpack' } ]
    build_linux_debian9:
        <<: *build_image
        environment: [ { DOCKER_PATH: './linux/debian9/buildpack', DOCKER_TAG: 'debian9-buildpack' } ]

    fan_in_1:
        <<: *fan_in

    build_dotnet11:
        <<: *build_image
        environment: [ { DOCKER_PATH: './dotnet/1.1', DOCKER_TAG: 'dotnet1.1-debian8' } ]
    build_dotnet20:
        <<: *build_image
        environment: [ { DOCKER_PATH: './dotnet/2.0', DOCKER_TAG: 'dotnet2.0-debian8' } ]
    build_dotnet21:
        <<: *build_image
        environment: [ { DOCKER_PATH: './dotnet/2.1', DOCKER_TAG: 'dotnet2.1-debian8' } ]
    build_dotnet22:
        <<: *build_image
        environment: [ { DOCKER_PATH: './dotnet/2.2', DOCKER_TAG: 'dotnet2.2-debian9' } ]

    fan_in_2:
        <<: *fan_in

    build_awscli1_11:
        <<: *build_image
        environment: [ { DOCKER_PATH: './tools/awscli/1.11', DOCKER_TAG: 'awscli1.11' } ]
    build_awscli1_14:
        <<: *build_image
        environment: [ { DOCKER_PATH: './tools/awscli/1.14', DOCKER_TAG: 'awscli1.14' } ]
    build_awscli1_16:
        <<: *build_image
        environment: [ { DOCKER_PATH: './tools/awscli/1.16', DOCKER_TAG: 'awscli1.16' } ]
    build_terraform0_11:
        <<: *build_image
        environment: [ { DOCKER_PATH: './tools/terraform/0.11', DOCKER_TAG: 'terraform0.11' } ]
    build_terraform0_12:
        <<: *build_image
        environment: [ { DOCKER_PATH: './tools/terraform/0.12', DOCKER_TAG: 'terraform0.12' } ]
    build_docker17_06:
        <<: *build_image
        environment: [ { DOCKER_PATH: './tools/docker/17.06', DOCKER_TAG: 'docker17.06' } ]
    build_docker18_03:
        <<: *build_image
        environment: [ { DOCKER_PATH: './tools/docker/18.03', DOCKER_TAG: 'docker18.03' } ]

    fan_in_3:
        <<: *fan_in

    build_python_27_debian9:
        <<: *build_image
        environment: [ { DOCKER_PATH: './python/2.7-debian', DOCKER_TAG: 'python2.7-debian9' } ]
    build_python_27_centos7:
        <<: *build_image
        environment: [ { DOCKER_PATH: './python/2.7', DOCKER_TAG: 'python2.7-centos7' } ]
    build_python_36_debian9:
        <<: *build_image
        environment: [ { DOCKER_PATH: './python/3.6-debian', DOCKER_TAG: 'python3.6-debian9' } ]
    build_python_36_centos7:
        <<: *build_image
        environment: [ { DOCKER_PATH: './python/3.6', DOCKER_TAG: 'python3.6-centos7' } ]

    fan_in_4:
        <<: *fan_in

    build_node_48:
        <<: *build_image
        environment: [ { DOCKER_PATH: './node/4.8', DOCKER_TAG: 'node4.8-centos7' } ]
    build_node_613:
        <<: *build_image
        environment: [ { DOCKER_PATH: './node/6.13', DOCKER_TAG: 'node6.13-centos7' } ]
    build_node_810:
        <<: *build_image
        environment: [ { DOCKER_PATH: './node/8.10', DOCKER_TAG: 'node8.10-centos7' } ]
    build_node_1010:
        <<: *build_image
        environment: [ { DOCKER_PATH: './node/10.10', DOCKER_TAG: 'node10.10-debian9' } ]

    fan_in_5:
        <<: *fan_in

    build_php_56:
        <<: *build_image
        environment: [ { DOCKER_PATH: './php/5.6', DOCKER_TAG: 'php5.6-centos7' } ]
    build_php_70:
        <<: *build_image
        environment: [ { DOCKER_PATH: './php/7.0', DOCKER_TAG: 'php7.0-centos7' } ]
    build_php_71:
        <<: *build_image
        environment: [ { DOCKER_PATH: './php/7.1', DOCKER_TAG: 'php7.1-centos7' } ]
    build_php_72:
        <<: *build_image
        environment: [ { DOCKER_PATH: './php/7.2', DOCKER_TAG: 'php7.2-centos7' } ]
    build_php_73:
        <<: *build_image
        environment: [ { DOCKER_PATH: './php/7.3', DOCKER_TAG: 'php7.3-debian9' } ]


    fan_in_6:
        <<: *fan_in

    build_elixir_12:
        <<: *build_image
        environment: [ { DOCKER_PATH: './elixir/1.2', DOCKER_TAG: 'elixir1.2-centos7' } ]
    build_elixir_13:
        <<: *build_image
        environment: [ { DOCKER_PATH: './elixir/1.3', DOCKER_TAG: 'elixir1.3-centos7' } ]
    build_elixir_14:
        <<: *build_image
        environment: [ { DOCKER_PATH: './elixir/1.4', DOCKER_TAG: 'elixir1.4-centos7' } ]
    build_elixir_15:
        <<: *build_image
        environment: [ { DOCKER_PATH: './elixir/1.5', DOCKER_TAG: 'elixir1.5-centos7' } ]
    build_elixir_16:
        <<: *build_image
        environment: [ { DOCKER_PATH: './elixir/1.6', DOCKER_TAG: 'elixir1.6-centos7' } ]
