version: 2.1

orbs:
  docker: circleci/docker@1.4.0

executors:
  default_executor:
    working_directory: '~/project'
    docker:
      - image: 'circleci/python:3.7'
    environment:
      - GCHR_IMAGE: 'hal-platform/hal-build-environments'
      - GCHR_REGISTRY: 'ghcr.io'
      - DCR_IMAGE: 'halplatform/hal-build-environments'
      - DCR_REGISTRY: 'docker.io'

workflows:
    version: 2
    pipeline:
        jobs:
            - fetch_code:
                filters:
                    branches: { only: master }

            - build_image:
                name: 'build_linux_centos6'
                path: './linux/centos6/buildpack'
                tag: 'centos6-buildpack'
                requires: [ fetch_code ]
            - build_image:
                name: 'build_linux_centos7'
                path: './linux/centos7/buildpack'
                tag: 'centos7-buildpack'
                requires: [ fetch_code ]
            - build_image:
                name: 'build_linux_debian8'
                path: './linux/debian8/buildpack'
                tag: 'debian8-buildpack'
                requires: [ fetch_code ]
            - build_image:
                name: 'build_linux_debian9'
                path: './linux/debian9/buildpack'
                tag: 'debian9-buildpack'
                requires: [ fetch_code ]
            - build_image:
                name: 'build_linux_debian10'
                path: './linux/debian10/buildpack'
                tag: 'debian10-buildpack'
                requires: [ fetch_code ]

            - fan_in:
                name: 'fan_in_1'
                requires:
                    - build_linux_centos6
                    - build_linux_centos7
                    - build_linux_debian8
                    - build_linux_debian9
                    - build_linux_debian10

            - build_image:
                name: 'build_dotnet11'
                path: './dotnet/1.1'
                tag: 'dotnet1.1-debian8'
                requires: ['fan_in_1']
            - build_image:
                name: 'build_dotnet20'
                path: './dotnet/2.0'
                tag: 'dotnet2.0-debian8'
                requires: ['fan_in_1']
            - build_image:
                name: 'build_dotnet21'
                path: './dotnet/2.1'
                tag: 'dotnet2.1-debian8'
                requires: ['fan_in_1']
            - build_image:
                name: 'build_dotnet22'
                path: './dotnet/2.2'
                tag: 'dotnet2.2-debian9'
                requires: ['fan_in_1']
            - build_image:
                name: 'build_dotnet31'
                path: './dotnet/3.1'
                tag: 'dotnet3.1-debian10'
                requires: ['fan_in_1']

            - fan_in:
                name: 'fan_in_2'
                requires:
                    - build_dotnet11
                    - build_dotnet20
                    - build_dotnet21
                    - build_dotnet22
                    - build_dotnet31

            - build_image:
                name: 'build_awscli1_11'
                path: './tools/awscli/1.11'
                tag: 'awscli1.11'
                requires: ['fan_in_2']
            - build_image:
                name: 'build_awscli1_14'
                path: './tools/awscli/1.14'
                tag: 'awscli1.14'
                requires: ['fan_in_2']
            - build_image:
                name: 'build_awscli1_16'
                path: './tools/awscli/1.16'
                tag: 'awscli1.16'
                requires: ['fan_in_2']
            - build_image:
                name: 'build_terraform0_11'
                path: './tools/terraform/0.11'
                tag: 'terraform0.11'
                requires: ['fan_in_2']
            - build_image:
                name: 'build_terraform0_12'
                path: './tools/terraform/0.12'
                tag: 'terraform0.12'
                requires: ['fan_in_2']
            - build_image:
                name: 'build_docker17_06'
                path: './tools/docker/17.06'
                tag: 'docker17.06'
                requires: ['fan_in_2']
            - build_image:
                name: 'build_docker18_03'
                path: './tools/docker/18.03'
                tag: 'docker18.03'
                requires: ['fan_in_2']
            - build_image:
                name: 'build_docker19_03'
                path: './tools/docker/19.03'
                tag: 'docker19.03'
                requires: ['fan_in_2']

            - fan_in:
                name: 'fan_in_3'
                requires:
                    - build_awscli1_11
                    - build_awscli1_14
                    - build_awscli1_16
                    - build_terraform0_11
                    - build_terraform0_12
                    - build_docker17_06
                    - build_docker18_03
                    - build_docker19_03

            - build_image:
                name: 'build_python_27_debian9'
                path: './python/2.7-debian'
                tag: 'python2.7-debian9'
                requires: ['fan_in_3']
            - build_image:
                name: 'build_python_27_centos7'
                path: './python/2.7'
                tag: 'python2.7-centos7'
                requires: ['fan_in_3']
            - build_image:
                name: 'build_python_36_debian9'
                path: './python/3.6-debian'
                tag: 'python3.6-debian9'
                requires: ['fan_in_3']
            - build_image:
                name: 'build_python_36_centos7'
                path: './python/3.6'
                tag: 'python3.6-centos7'
                requires: ['fan_in_3']

            - fan_in:
                name: 'fan_in_4'
                requires:
                    - build_python_27_debian9
                    - build_python_27_centos7
                    - build_python_36_centos7
                    - build_python_36_debian9

            - build_image:
                name: 'build_node_48'
                path: './node/4.8'
                tag: 'node4.8-centos7'
                requires: ['fan_in_4']
            - build_image:
                name: 'build_node_613'
                path: './node/6.13'
                tag: 'node6.13-centos7'
                requires: ['fan_in_4']
            - build_image:
                name: 'build_node_810'
                path: './node/8.10'
                tag: 'node8.10-centos7'
                requires: ['fan_in_4']
            - build_image:
                name: 'build_node_1010'
                path: './node/10.10'
                tag: 'node10.10-debian9'
                requires: ['fan_in_4']
            - build_image:
                name: 'build_node_1212'
                path: './node/12.12'
                tag: 'node12.12-debian10'
                requires: ['fan_in_4']

            - fan_in:
                name: 'fan_in_5'
                requires:
                    - build_node_48
                    - build_node_613
                    - build_node_810
                    - build_node_1010
                    - build_node_1212

            - build_image:
                name: 'build_php_56'
                path: './php/5.6'
                tag: 'php5.6-centos7'
                requires: ['fan_in_5']
            - build_image:
                name: 'build_php_70'
                path: './php/7.0'
                tag: 'php7.0-centos7'
                requires: ['fan_in_5']
            - build_image:
                name: 'build_php_71'
                path: './php/7.1'
                tag: 'php7.1-centos7'
                requires: ['fan_in_5']
            - build_image:
                name: 'build_php_72'
                path: './php/7.2'
                tag: 'php7.2-centos7'
                requires: ['fan_in_5']
            - build_image:
                name: 'build_php_73'
                path: './php/7.3'
                tag: 'php7.3-debian9'
                requires: ['fan_in_5']
            - build_image:
                name: 'build_php_74'
                path: './php/7.4'
                tag: 'php7.4-debian10'
                requires: ['fan_in_5']

            - fan_in:
                name: 'fan_in_6'
                requires:
                    - build_php_56
                    - build_php_70
                    - build_php_71
                    - build_php_72
                    - build_php_73
                    - build_php_74

            - build_image:
                name: 'build_elixir_12'
                path: './elixir/1.2'
                tag: 'elixir1.2-centos7'
                requires: ['fan_in_6']
            - build_image:
                name: 'build_elixir_13'
                path: './elixir/1.3'
                tag: 'elixir1.3-centos7'
                requires: ['fan_in_6']
            - build_image:
                name: 'build_elixir_14'
                path: './elixir/1.4'
                tag: 'elixir1.4-centos7'
                requires: ['fan_in_6']
            - build_image:
                name: 'build_elixir_15'
                path: './elixir/1.5'
                tag: 'elixir1.5-centos7'
                requires: ['fan_in_6']
            - build_image:
                name: 'build_elixir_16'
                path: './elixir/1.6'
                tag: 'elixir1.6-centos7'
                requires: ['fan_in_6']

jobs:
    fetch_code:
        executor: default_executor
        steps:
            - checkout
            - persist_to_workspace:
                root: '.'
                paths: [ '.' ]

    fan_in:
        executor: default_executor
        steps:
            - run: 'whoami'

    build_image:
        parameters:
            path:
                type: string
            tag:
                type: string

        executor: default_executor
        steps:
            - attach_workspace:
                at: '.'

            - setup_remote_docker

            - docker/check:
                registry: "${GCHR_REGISTRY}"
                docker-username: GHCR_USER
                docker-password: GHCR_PASS
            - docker/check:
                registry: "${DCR_REGISTRY}"
                docker-username: DOCKER_USER
                docker-password: DOCKER_PASS

            - docker/build:
                path: '<< parameters.path >>'
                image: "${DCR_IMAGE}"
                tag: '<< parameters.tag >>'
            - run:
                name: 'Retag image'
                command: |
                    docker tag \
                        "${DCR_REGISTRY}/${DCR_IMAGE}:<< parameters.tag >>" \
                        "${GCHR_REGISTRY}/${GCHR_IMAGE}:<< parameters.tag >>"

            - docker/push:
                registry: "${GCHR_REGISTRY}"
                image: "${GCHR_IMAGE}"
                tag: '<< parameters.tag >>'
            - docker/push:
                registry: "${DCR_REGISTRY}"
                image: "${DCR_IMAGE}"
                tag: '<< parameters.tag >>'
